ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/char
#include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-y	:=  stk8baxx_driver.o

